### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by pira2071** [pira2071/graduation_work_trip_app#25]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。
旅行計画の立案・共有や旅行中の写真の共有などを補助するアプリケーションです。
友人や恋人など複数人で旅行の計画を立てられるように、旅行メンバー全員から観光スポットや宿泊先の提案を募ることができ、提案された内容を利用してスケジュール表を簡単に作成・共有することができます。
また、観光スポットごとに写真を掲載・共有したり、宿泊料金やレンタカー料金などを立替払いした場合の各旅行メンバーへの請求額をお知らせすることもできます（以下、旅行計画機能について説明。その他機能は省略。）。
・旅行ごとにスケジュールや写真を共有できるようにする（例えば「２０２３鎌倉旅行」や「２０２４宮崎旅行」のように各旅行ごとにアプリ内で枠を作成することができるようにする）。
・計画を起案した人（起案とは、具体的には、前述の機能にあるようにその旅行の枠を作成すること）に「プランナー（幹事役）」というロールを自動で設定する。
・「プランナー」は、「旅行名」と「旅行日（何年何月何日〜何月何日）」、旅行メンバー（メンバーは後からでも追加可能）を入力することで新規の枠を立てることができるようにする。
・旅行メンバーはあらかじめ友達登録している自分の友達リストからしか選択できないようにする。そのため、友達検索機能と友達追加機能も搭載する予定である。
・その旅行メンバーとして追加された者には、そのアプリ内のプラン一覧画面に、その旅行の枠が表示されるようになり、その枠を選択して、「参加しますか？」に「はい」と選択して参加する。この参加により、招待された者には「ゲスト（幹事以外の旅行メンバー）」としてのロールが自動で設定される。
・「プランナー」は、「ゲスト」に対して、「観光スポット」、「宿泊先」、「食事処」、「移動手段」の４項目について提案を求めることができるようにする（当然「プランナー」も提案することができるようにする。）。この提案を求めるに当たっては、幹事から提案に際しての留意事項をメッセージとして、登録することができ、また、提案の締め切り期限を設けることもでき、締め切り日にリマインド通知が自動で行われるようにする。
・提案するスポットは、本アプリとGooglemapsを連携し、Googlemapsの検索フォームで検索した場所を追加ボタンを押すことで、提案内容が一覧として表示される表（フレーム）に反映させられるような仕組みにする。追加された提案内容の場所は、当該アプリ内に表示された地図上に、自動でマーキングされるようにする。また、提案された順に昇順で番号を自動で振っていくようにし、その番号が地図上にも表示されるようにする。
・「プランナー」が決定したスポットを日程に組み込んで、「ゲスト」に「提案」する。提案に対して、「ゲスト」は「意義なし」や「意見する」などを選択することができる。日程に組み込むとは、具体的には、提案されたスポットを画面上で押下すると、「何日目」と「時間帯」を選択することができ、それを選べば、タイムスケジュールの様式に日程がはめ込まれていき、タイムスケジュール表ができあがるようになる。なお、「時間帯」については、具体的な時間帯を指定するのではなく、「朝・昼・夜」の選択肢から選ぶような設定にする。
・作成した旅程表は、旅行メンバー全員に共有され印刷ができるようにする。

■1週間辺りの開発に向けられる時間
- 1週間あたり：30時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。
https://github.com/users/pira2071/projects/1

■MVPリリースまで

開発環境のセットアップと基本設定
- [ ] Docker環境構築
- [ ] Ruby/Rails環境設定
- [ ] PostgreSQL設定
- [ ] RedisとSidekiq設定

AWSインフラ環境の構築
- [ ] VPC設定
- [ ] EC2インスタンス作成
- [ ] RDS設定
- [ ] S3バケット作成
- [ ] Route53設定
- [ ] ELB設定

ユーザー認証・認可機能の実装
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワードリセット機能
- [ ] ユーザー情報編集機能
- [ ] 友達管理機能

旅行フレームの基本機能実装
- [ ] フレーム作成機能
- [ ] メンバー招待機能
- [ ] メンバー参加確認機能
- [ ] フレーム一覧表示
- [ ] フレーム詳細表示

場所提案機能の実装
- [ ] Google Maps API連携設定
- [ ] 地図表示コンポーネント作成
- [ ] 場所検索機能実装
- [ ] 提案募集機能実装
- [ ] 提案投稿機能実装
- [ ] 提案一覧表示機能実装
- [ ] 投票機能実装

旅程表機能の実装
- [ ] 旅程表テンプレート作成
- [ ] 日程管理機能実装
- [ ] 時間帯管理実装
- [ ] ドラッグ&ドロップ機能実装
- [ ] 旅程表保存機能実装
- [ ] 確定機能実装

通知システムの実装
- [ ] 通知作成機能実装
- [ ] 通知一覧表示実装
- [ ] メール通知機能実装
- [ ] リアルタイム通知実装

■MVP後

写真共有と持物リスト機能の実装
- [ ] S3連携実装
- [ ] 写真アップロード機能実装
- [ ] アルバム表示機能実装
- [ ] 持物リスト作成機能実装
- [ ] チェック機能実装

精算機能の実装
- [ ] 請求作成フォーム実装
- [ ] 内訳登録機能実装
- [ ] 請求一覧表示機能実装
- [ ] 精算状態管理機能実装

■MVPレビュー依頼予定日
予定日：2025年12月15日

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

**Comment by TakenakaEri** [comment]
LGMTです！
この後発生した追加issueに関しては、ご自身の判断で追加していただいて問題ありません！
